### ISSUE TITLE
FORD for documentation

### ISSUE THREAD

**Issue by jacobwilliams** [jacobwilliams/json-fortran#114]
Consider switching the api documentation generation from [Robodoc](https://github.com/gumpu/ROBODoc) to [FORD](https://github.com/cmacmackin/ford). Ford has a lot of features I like better, and seems to be more actively developed.  I'll test it out on a separate branch.

**Comment by zbeekman** [comment]
I like FORD too. I’m worried it will be tedious to transition, but totally support moving to FORD

**Comment by jacobwilliams** [comment]
FYI.  See [here](https://github.com/cmacmackin/ford/issues/45).

**Comment by zbeekman** [comment]
Have you tried re-running the travis tests with the latest version of FORD? Once you have FORD configured etc. I’m happy to help with updating the build scripts. Just let me know.

**Comment by zbeekman** [comment]
I just ran the build.sh script locally and it seems to build the documentation as expected and FORD seems to be working nicely save a small bug with linking to .F90 source files from the top menu/header.

**Comment by jacobwilliams** [comment]
Yes, I've got it just about how I want it on the ford branch...I just want to do a few more teaks.  I'll definitely need you to fix the documentation deployment part of the travis file.  Can you do a pull request on the ford branch? Is such a thing possible?

**Comment by zbeekman** [comment]
It sure is possible! The tricky thing is that the documentation deployment behaves differently for master/branch/tag so even if I submit a PR against the FORD branch we won't know for sure if it works until it's merged with master. Also, I'll need to update the CMake build, and once a new release is tagged, submit a PR for updating the Homebrew formula.

**Comment by zbeekman** [comment]
What do we want to do about tags vs master documentation, as well as legacy documentation? There is a way to generate pure markdown pages, we could point to the tags from there and maybe dump the old documentation in a sub directory and each tag in a sub directory.

**Comment by jacobwilliams** [comment]
I like the basic system that we havenow, where all the old release documentation is available, and also the current master branch.  I'm OK with any improvements you want to make to that. The basic page design could be made more awesome, since it is sort of lame right now.

**Comment by zbeekman** [comment]
OK, I think that we should take advantage of the page_dir feature to put up test coverage info generated by FoBiS.py, contributing guide lines and the README.md. We can also create some type of landing page there, or just have people land on the master branch page and link to tags from there. I think that the landing page can definitely be generated by FORD though, because the current one is a little sad. Also, the wiki is markdown and can be checked out with git, so it’s possible that it could be duped over to the `page_dir` tree for convenience, since it could hold more detailed installation and usage documentation, etc.

I have the CMake build almost completely updated, I’m just working on adding some logic to prevent unnecessary rebuilds of the FORD documentation since it take a while to generate. I also cleaned up build.sh some more and removed some old FoBiS.py work arounds that have been fixed.

I tried to update the SCons file but SCons mystifies me. I’m not even sure that the current implementation was working 100% correctly for the documentation building logic and the installation logic. My Python is pretty weak, so maybe someone else might have more success.

**Comment by zbeekman** [comment]
**Update:**

The CMake build is up to date, and I’ve implemented some logic to make sure that the documentation is not rebuilt unless it needs to be, both at “configure” time, via caching the dynamically computed outputs, and at build time via correctly generated makefile dependencies. I’ve made some tweaks to build.sh to clean it up for FORD and getting rid of some old FoBiS.py work arounds. I still have yet to update the deployment script but will try to get to that soon. You should figure out what you want to do about updating the SCons build system. We could ask Bruce to update it or drop support for it.

Also, are you planning to convert the unit tests’ documentation to FORD? I can try to help with that after finishing the build script updates.

**Comment by zbeekman** [comment]
second update: I just figured out why he travis builds were failing and fixed it. I’m going to go ahead and submit an incremental PR now. The deployment script still hasn’t been updated but at least now as we hack we can see the effects on the build and test coverage.

**Comment by jacobwilliams** [comment]
Thanks! I'll start to look at this again later in the week... I can do the unit tests.

**Comment by zbeekman** [comment]
take your time… I’ve just been pushing some updates to the PR as I implement them. Still haven’t tackled the deployment.

**Comment by zbeekman** [comment]
What are your thoughts on including the README.md via `{!README.md!}` into the `json-module.md` FORD file?

**Comment by zbeekman** [comment]
I think I have come up with a strategy to house the old documentation and for deploying on commits to master and new tags.

BTW, check this [automatic changelog generator](https://github.com/skywinder/github-changelog-generator) out. I think that we [should probably keep a changelog](http://keepachangelog.com). We can include it in the FORD documentation.

Also, it would be helpful to go back and tag old closed issues as questions, enhancements, invalid etc. so that they end up in the right place in the changelog.

**Comment by zbeekman** [comment]
PR #137 pretty much finishes up everything, except changing the test documentation. Since there are some pretty big improvements/fixes in #137 I would vote that we merge the ‘ford’ branch with master now to propagate those through. We can leave this issue open until the FORD documentation of unit tests is finished, but I won’t be able to help with that, aside from the occasional trouble shooting.

**Comment by jacobwilliams** [comment]
Great job on everything!!  I haven't had time to do much (except accept all your pull requests). Will try to do the unit tests soon.

**Comment by zbeekman** [comment]
No hurry, the main API documentation is the most important bit. I can take care of the Homebrew update the next time you tag a release too.

**Comment by jacobwilliams** [comment]
Done. We can continue to tweak it as needed.

**Comment by zbeekman** [comment]
Great! Don’t forget to adjust the exclude meta data in the FORD project file, so that we can actually use the fruits of your labor.
