### ISSUE TITLE
Help on writing Fortran arrays to json

### ISSUE THREAD

**Issue by LeiShi** [jacobwilliams/json-fortran#132]
Hi, 

I'm trying to use JSON as a standard output format for a Fortran simulation code. This module is exactly what I need. However, I didn't see an example on writing Fortran arrays directly. By fortran arrays, I mean the variables defined by "dimension". The only example of writing vectors I saw, was like this "json_print(p,'ints',[1,2,3])". Would you please provide some guide on this?

I'm not very familiar with Fortran. I'm just developing an interface for an existing Fortran code. So if there is an obvious answer, please kindly point it out.

Thanks a lot!

**Comment by zbeekman** [comment]
Hi @LeiShi, I’m working on a more detailed response right now, but just wanted to let you know the gist of what you need to do.

To add a child array object, named ‘data’ to some parent object you can just use `json_add()` with the `reshape()` intrinsic to transform any multidimensional arrays into 1-D arrays. (To my knowledge JSON has no notion of multi-dimensional arrays, so you can encode the dimensionality data in meta data you add to the json object.) The only tricky things to remember are that

 1. Fortran is a column major language (unlike C which is row major)
 1. `reshape()` outputs the new array in “array element order” (column major order)
 1. The second argument to `reshape()` is a 1-D array holding the dimensions of the desired output array (not a scalar)

```fortran
type(json_value), pointer :: parent
real(wp) :: data(5,3,4)
! …
call json_add( parent, 'dim 1', size(data,dim=1) ) ! dim1, i, is 5
call json_add( parent, 'dim 2', size(data,dim=2) ) ! dim2, j, is 3
call json_add( parent, 'dim 3', size(data,dim=3) ) ! dim3, k, is 4
call json_add( parent, 'size', size(data) ) ! total array size = 60 elements
call json_add( parent, 'array data’, reshape( data, [ size(data) ] ) )
! reshape(data, [ size(data) ]) = [ (1,1,1), (2,1,1), …, (5,1,1), (1,2,1), (2,2,1), … ]^T
```

**Comment by zbeekman** [comment]
There is a way to do this, but, note that JSON has no notion of multi-dimensional arrays that I am aware of, so you’ll need to write the array dimensions as some sort of meta data of a JSON object and then write the array in *array element order*[<sup>1</sup>](#user-content-footnote1). N.B. that Fortran is a [*column major*](https://en.wikipedia.org/wiki/Row-major_order) language whereas C and many others are *row* major.

```fortran
program test_12

  integer,parameter :: imx = 5, jmx = 3, kmx = 4 !! dimensions for raw work array of primitive type
  type(json_value), pointer :: root, meta_array  !! json nodes to work with
  real(wp) :: raw_array(imx,jmx,kmx)             !! raw work array
  integer :: i,j,k                               !! loop indices

  call json_initialize(real_format='G')

  ! populate the raw array
  forall (i=1:imx,j=1:jmx,k=1:kmx) ! could use size(... , dim=...) instead of constants
     raw_array(i,j,k) = i + (j-1)*imx + (k-1)*imx*jmx
  end forall

  call json_create_object(root,dir//file)
  call json_create_object(meta_array,'array data')
  call json_add(meta_array, 'i dimension', size(raw_array,dim=1))
  call json_add(meta_array, 'j dimension', size(raw_array,dim=2))
  call json_add(meta_array, 'k dimension', size(raw_array,dim=3))
  call json_add(meta_array, 'total size', size(raw_array))

  ! now add the array
  ! N.B. `json_add()` only accepts 1-D arrays and scalars, so transform with `reshape`
  ! N.B. reshape populates new array in "array element order".
  ! C.F. "Modern Fortran Explained", by Metcalf, Cohen and Reid, p. 24.
  ! N.B. Fortran is a column major language

  call json_add( meta_array, 'data', reshape( raw_array, [ size(raw_array) ] ) )
  ! now put it all together
  call json_add(root,meta_array)

  call json_print(root,output_unit)

end program
```
 
This program will print the following JSON structure to `stdout`:

```json
{
  "array data": {
    "i dimension": 5,
    "j dimension": 3,
    "k dimension": 4,
    "total size": 60,
    "data": [
      1.0,
      2.0,
      3.0,
      4.0,
      5.0,
      6.0,
      7.0,
      8.0,
      9.0,
      10.0,
      11.0,
      12.0,
      13.0,
      14.0,
      15.0,
      16.0,
      17.0,
      18.0,
      19.0,
      20.0,
      21.0,
      22.0,
      23.0,
      24.0,
      25.0,
      26.0,
      27.0,
      28.0,
      29.0,
      30.0,
      31.0,
      32.0,
      33.0,
      34.0,
      35.0,
      36.0,
      37.0,
      38.0,
      39.0,
      40.0,
      41.0,
      42.0,
      43.0,
      44.0,
      45.0,
      46.0,
      47.0,
      48.0,
      49.0,
      50.0,
      51.0,
      52.0,
      53.0,
      54.0,
      55.0,
      56.0,
      57.0,
      58.0,
      59.0,
      60.0
    ]
  }
}
```

<sup id="footnote1">1</sup> Array element order is obtained by incrementing the array indices on the left before those to the right.

**Comment by LeiShi** [comment]
Hi @zbeekman,

Thanks a lot for your detailed answer! This is exactly what I am looking for. 
One further question about adding 1D array using json_add. It seems there is no need to specify the actual size of the array, does this mean json_add can obtain this information automatically? Or when I pass an array, I'm not passing just a pointer, but the whole trunk of data? Can I pass a slice of the array directly? 

I noticed that JSON can have a nested array structure, which may be used for storing multi-dimensional arrays. Are you gonna consider make it a standard output form for Fortran arrays?

Thanks again for your help!

**Comment by zbeekman** [comment]
> One further question about adding 1D array using json_add. It seems there is no need to specify the actual size of the array, does this mean json_add can obtain this information automatically? Or when I pass an array, I'm not passing just a pointer, but the whole trunk of data? Can I pass a slice of the array directly?

There is no need to specify the size of the array, due to the use of “assumed-shape arrays”, a Fortran (>= 90) language feature. (However, it MUST be 1-D, or rank 1 in Fortran terms.) Fortran (>= 90) encodes the array bounds  and shape in the array object itself. Fortran 90 introduced “Assumed-shape arrays” which is a “non-allocatable non-pointer dummy argument array that takes its shape from its effective argument”. (Prior to Fortran 90, there were “assumed-size arrays” whose behavior was kinda, sorta similar, except that it would always transform multi-dimensional arrays into 1D arrays.)

The semantics of Fortran dummy and actual arguments are different than C’s, and Fortran is a more abstract, higher level language (at least modern Fortran is…). Therefore, there’s usually no need to worry about “pass by reference” and “pass by value” type of concerns. The compiler looks at the dummy arguments `intent()` attributes and figures out what operations are needed.

Yes, you can pass “array sections” (Fortran term for array slices) and the compiler will usually end up doing copy in, copy out. In the above example I could have written this instead:

```fortran
call json_add( meta_array, ‘data’, reshape( raw_array(2:4,1:2,2:3), [ size( raw_array(2:4,1:2,2:3) ) ] ) )
```

> I noticed that JSON can have a nested array structure, which may be used for storing multi-dimensional arrays. Are you gonna consider make it a standard output form for Fortran arrays?

JSON-Fortran currently has all the API functionality required to do this yourself, however we do not have any convenience routines to accomplish this at this time. In the future we may consider this if @jacobwilliams likes the idea (he is the BDFL of JSON-Fortran), especially as compiler support for the Fortran 2008 “assumed rank” dummy arguments are adopted. Without “assumed rank” you need to write an interface for every possible array rank, and I forget what the maximum is now, but it is quite a few. I think one of the recent standards increased it to over 15-D! If this feature would be helpful/critical/heavily used by your application, then feel free to open a separate issue as a feature request.

**Comment by zbeekman** [comment]
Also, vis, arrays of 1-D arrays, I personally think that flat is often better than nested and that there is limited utility in moving away from 1-D arrays, at least for primitive variables… just my $0.02

**Comment by LeiShi** [comment]
Hi @zbeekman,

Thank you very much! 
In my current work, I only need to deal with 1D arrays, so the current state of the module is totally fine for my use. 

Best regards.
