### ISSUE TITLE
Name mangling issue with intel fortran

### ISSUE THREAD

**Issue by appleparan** [jacobwilliams/json-fortran#152]
First, I'm using Intel Fortran 12.1.0 20110811. I have succeed build and test. Tests working good, However, when I'm trying to link json-fortran, I got errors.

1. just including module is alright
When I just wrote `use json_module` and add include path & static library (`libjsonfortran.a`) to my compile & link option, it is fine. nothing happend.

2. Simple printing json file. 
```

        ! initialize the module
        call json_initialize()

        ! read the file
        call json%load_file(filename = '../files/inputs/test1.json')

        ! print the file to the console
        call json%print_file()

        ! clean up
        call json%destroy()
        if (json_failed()) stop 1

```
When  I just ran this code (with variable declaration and use modules), I got 'undefined reference to` error (well-known linking error, which means the program finds declaration but the implementation is not exists. ) 
```
/home/ycse02/appleparan/src/patit/obj/IO/read_param.o: In function `read_param':
/home/ycse02/appleparan/src/patit/src/IO/read_param.f90:29: undefined reference to `json_module_MP_json_initialize_'
/home/ycse02/appleparan/src/patit/src/IO/read_param.f90:32: undefined reference to `json_module_MP_json_file_load_'
/home/ycse02/appleparan/src/patit/src/IO/read_param.f90:34: undefined reference to `json_module_MP_json_file_print_to_console_'
/home/ycse02/appleparan/src/patit/src/IO/read_param.f90:93: undefined reference to `json_module_MP_json_file_destroy_
```

weird thing is `_MP_` 

I also did 'nm -s libjsonfortran.a' and there were all `_mp_` infixes in module procedure. (I know this is related to ifort's name mangling)
```
00000000000251f0 T json_module_mp_get_current_line_from_file_stream_
```
3. When I also added `get` procedures, like `call json%get('version.major', i, found)` statements, in my code, I got compilation error like this.

```
/home/ycse02/appleparan/src/patit/src/IO/read_param.f90(36): error #8486: There is no matching specific subroutine for this type bound generic subroutine call.   [GET]
    call json%get('fname_input', fname_in, json_found)
```

I thought compiler didn't find appropriate subroutine for `get` (because it is generic). Moreover, I assumed that this problem still be with strange `_MP_` infixes. Why this library has uppercase `_MP_` infixes? I used `FoBiS` to build `json-fortran`. Is this a `FoBiS` problem? or `FoBiS` option given in `build.sh`?

**Comment by appleparan** [comment]
Would you give me a file which has only interfaces like FFTW (good example)? I think [this link](http://fedoraproject.org/wiki/PackagingDrafts/FortranLibraries#Fully_Module-Based_Libraries) will be helpful

**Comment by zbeekman** [comment]
First of all, ifort < 13.1 are not officially supported, nor are they guaranteed to work. However, if you run the `build.sh` script and all the tests pass, then it *should* :pray: be ok, I *think*.

Now, to diagnose the other issues, I need to see how you compiled and linked your code, and what commands you ran to build, and possibly install JSON-Fortran. Please show this information.

**Comment by appleparan** [comment]
Yes, due to success of tests, `json-fortran` should be worked under ifort 12.1. 
Here is my [Makefile](https://gist.github.com/appleparan/8f99a201ac783ca45b87) It is quite simple. You could see FFLAGS, LDFLAGS, LDLIBS, and LFLAGS for compilation and linking option.

**Comment by zbeekman** [comment]
Quite simple!? Sigh, makefiles are a great source of frustration... In the mean time, I *HIGHLY* recommend [CMake](http://cmake.org) due to it's automatic dependency resolution etc. powerful system introspection features and easy setup for linking against JSON-Fortran, as described in the [CMake example of the README](https://github.com/jacobwilliams/json-fortran#building-the-library).

I think there are two separate issues here:
 1. The linking issue
 1. The resolution of the generic `get` procedure.

For the first issue, it would  be very helpful if you could reduce your problem to a simpler case, preferably one that I can reproduce on my system. Looking at your makefile, I cannot tell how you have built json fortran, what files exist in the directory structure and I do not have access to your source files, etc. Without a complete working example, or a simpler reproducer, it is very difficult for me to find the source of your problem, but I am quite confident that the supposed "name mangling issue" is an issue with your Makefile/build system or compiler bug rather than with JSON-Fortran itself. The `_MP_` is standard ifort name mangling and proper compiler usage and adherence to the Fortran language standard should ensure that the "poor Fortran programmer" does not need to concern themselves with issues like name mangling. Alternatively, it could very well be an intel compiler bug, if you are using 12.x. The order of linker flags can be important, and has been a gotcha for me in the past so that is were I would look first.

As for the second issue: It appears that you can compile the client code fine, except for the resolution of the specific subroutine for the generic `get` interface. This is likely a legitimate issue in the usage from your code or a compiler bug, and I need to see the declarations for `fname_in` and `json_found` to verify which it is. You must ensure that the `get` method can resolve to [one of the specific get procedures](http://jacobwilliams.github.io/json-fortran/module/json_module.html#interface-json_get) and I suspect that you are not using a `character(kind=CK,len=:), allocatable` variable for `fname_in`. (It looks like the `get method` should resolve to [`json_get_string_with_path`](http://jacobwilliams.github.io/json-fortran/proc/json_get_string_with_path.html).)I am not sure if deferred length character variables are supported in 12.x and if they are there may very well be compiler bugs associated with them. The Intel compilers have been rife with bugs, and claimed to implement F2003/08 features, when in fact the implementation was not robust.

Good luck and send along

**Comment by zbeekman** [comment]
any luck?

**Comment by appleparan** [comment]
It was my problem. I enabled "[-standard-semantics](https://software.intel.com/en-us/node/525134)" option when compiling. It makes module separator "_mp_" as "_MP_". ref : https://software.intel.com/en-us/node/525354 

Intel Fortran Documentation said, "_mp_ is the separator between the module and entity names and is always lowercase (except when the assume std_mod_proc_name compiler option or standard-semantics compiler option is used)."

I removed "standard-option" then it works. Sorry for disturbance. However, I can confirm that your library works with ifort 12.1

**Comment by zbeekman** [comment]
huh, interesting... Did you also pass `-standard-semantics` when linking? The compiler should be self-consistent, if not I would classify that as a bug... OH, I see the library was built one way and the code compiled another.... Maybe a note about that should be added to the JSON-Fortran documentation somewhere...

**Comment by appleparan** [comment]
No I just passed when compiling. I think the reason why they capitalized `_mp_` as they don't want module separator `_mp_` conflicts user defined subroutine which contains `_mp_`. For example, if I made a subroutine as `do_something_mp_do_again` inside a certain module `mod_anything`, that make a problem because compiler recognize `do_something` as module. You can find this issue at [this link](http://computer-programming-forum.com/49-fortran/50fb395e8298e922.htm) and I saw a post in Intel Fortran forum that explain it is hard to fix implementation to change all `_mp_`s to `_MP_`s. It is intel fortran problem and I think it is good idea to make a documentation because it could affect all Intel Fortran versions. 

P.S. I don't understand why fortran standard committee makes module as binary. Not only this issue, making interface file as binary (module) is a bad idea because it depends on compilers (gfortran, ifort and so on.)

**Comment by zbeekman** [comment]
I'm glad to hear that you've sorted out the problems you were having. It sounds like this issue is resolved and the ticket may now be closed.

**Comment by appleparan** [comment]
Sure. I'm appreciated for your help

**Comment by jacobwilliams** [comment]
FYI: https://software.intel.com/en-us/forums/intel-fortran-compiler-for-linux-and-mac-os-x/topic/801093

Yes, we should mention this in the documentation as a quirk when using ifort. Possibly even have a way to enabled or disable this flag or add the `-assume nostd_mod_proc_name` one.
