### ISSUE TITLE
does json-fortran support c-style comment?

### ISSUE THREAD

**Issue by handrake0724** [jacobwilliams/json-fortran#234]
does json-fortran support c-style comment?

**Comment by zbeekman** [comment]
No. Comments in JSON files are not valid JSON syntax.

**Comment by zbeekman** [comment]
As a work around you could create dummy  kvps including this info. 
```json
{"__comment":"__comment my comment text here"}
```

**Comment by jacobwilliams** [comment]
I never really intended to add comment support since it isn't standard JSON. 

...But I do sometimes wish I could put comments in JSON config files. I know the [official](https://plus.google.com/+DouglasCrockfordEsq/posts/RK8qyGVaGSr) answer is that you can comment all you want, but you have to run it through a minifier to strip out the comments before you send it to a JSON parser. However, that extra step seems unsatisfactory for a poor Fortran user.

So....you never know...

**Comment by jacobwilliams** [comment]
I added it. Note that it only supports single-line comments denoted by a specified single character (use the `comment_char` argument of one of the initialize routines). For example if `comment_char='/'`, the following would parse fine:
```
{
 "a": [1,2,3] // it's an array
              // with three elements.
}
```

**Comment by zbeekman** [comment]
What happens if / is in a string in the JSON?

**Comment by jacobwilliams** [comment]
It handles that fine. It doesn't check for comments while parsing the strings.
