### ISSUE TITLE
Error when reading real array value

### ISSUE THREAD

**Issue by handrake0724** [jacobwilliams/json-fortran#236]
Let a jsong file as :
```json
{
  "x0" : [1.0, 2.0]
}
```
the code is as follows:
```fortran
use json_module
type(json_file) :: json
logical :: found
real, dimension(:), allocatable :: rArray

call json%get("x0", rArray, found)
```
I got the following error

There is no matching specific subroutine for this type bound generic subroutine call. [GET]

FYI, my compile environment is visual studio 2015 + intel compiler

**Comment by jacobwilliams** [comment]
Currently, JSON-Fortran only supports `real64` values (i.e., "double precision"). The real kind is exported by the library as `json_RK`, so you could declare your variable:
```fortran
real(json_rk), dimension(:), allocatable :: rArray
```
and it should work.

**Comment by handrake0724** [comment]
Thanks for the comment.

**Comment by zbeekman** [comment]
@handrake0724 if this resolves your problem, please close the issue.

@jacobwilliams I wonder what it would take to support single precision as well. All the get methods seem like they could be implemented with simple wrappers that call the double precision version and then convert to single before returning. There may be some complications with IO, i.e. matching IO precision to that used to put the value in the first place. Another potential difficulty with my proposed approach may be when single precision puts are followed by gets, depending on the specifics of the compilers type conversion/rounding. I don't know if the standard says anything about this.

**Comment by milancurcic** [comment]
@zbeekman @jacobwilliams FWIW it is at least straightforward to allow a single precision (instead of double precision) build of json-fortran by doing:
```fortran
    use,intrinsic :: iso_fortran_env, only: real32,real64,int32,logical_kinds
...
#ifdef REAL32
    integer,parameter,public :: RK = real32  !! Default real kind [4 bytes]
#else
    integer,parameter,public :: RK = real64  !! Default real kind [8 bytes]
#endif
```
in `src/json_kinds.F90`. This is what I do in my local copy of json-fortran because my top project needed to be able to work with single precision as well. So far it works as expected and did not notice any loss of precision. Since the top project needed exclusively single or double precision, but not both at the same time, this approach was satisfactory for me.

**Comment by zbeekman** [comment]
Yes adding such a build time option is trivial and should probably be
included in the mean time.

**Comment by jacobwilliams** [comment]
See also  #229. I just haven't had time to review it. My preference would be to use the @zbeekman approach, where they are stored as `real64` internally, and then there are just `real32` wrappers that do the conversion. The details would have to be worked out as indicated.

@milancurcic Yes, I like this. I could add this to the code. Then you could use it as-is without having to modify it.

What about `real128`? Should that also be a possibility?

**Comment by zbeekman** [comment]
We can use cmake to query for fortran real and integer kinds. It may make
sense to also allow big integers. On todays HPC systems this is
increasingly relevant as unstructured simulations can be run meshes large
enough to require usage of big integers (FUN3D for example)

On Fri, Nov 18, 2016 at 10:59 AM Jacob Williams <notifications@github.com>
wrote:

See also #229 <https://github.com/jacobwilliams/json-fortran/pull/229>. I
just haven't had time to review it. My preference would be to use the
@zbeekman <https://github.com/zbeekman> approach, where they are stored as
real64 internally, and then there are just real32 wrappers that do the
conversion. The details would have to be worked out as indicated.

@milancurcic <https://github.com/milancurcic> Yes, I like this. I could add
this to the code. Then you could use it as-is without having to modify it.

What about real128? Should that also be a possibility?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/jacobwilliams/json-fortran/issues/236#issuecomment-261567511>,
or mute the thread

**Comment by jacobwilliams** [comment]
So, for completeness, something like this:
```fortran
#ifdef REAL32
    integer,parameter,public :: RK = real32   !! Default real kind [4 bytes]
#elseif REAL64
    integer,parameter,public :: RK = real64   !! Default real kind [8 bytes]
#elseif REAL128
    integer,parameter,public :: RK = real128  !! Default real kind [16 bytes]
#else
    integer,parameter,public :: RK = real64   !! Default real kind if not specified [8 bytes]
#endif

#ifdef INT8
    integer,parameter,public :: IK = int8      !! Default integer kind [1 byte]
#elseif INT16
    integer,parameter,public :: IK = int16     !! Default integer kind [2 bytes]
#elseif INT32
    integer,parameter,public :: IK = int32     !! Default integer kind [4 bytes]
#elseif INT64
    integer,parameter,public :: IK = int64     !! Default integer kind [8 bytes]
#else
    integer,parameter,public :: IK = int32     !! Default integer kind if not specified [4 bytes]
#endif
```

**Comment by zbeekman** [comment]
Yes, and I'll insert come compiler introspection code into the cmake build
system to ensure that each requested kind type exists. If not, on the cmake
end, we can print an error/warning if a kind is requested at compile time
that isn't present.
