### ISSUE TITLE
Add library as a cmake submodule

### ISSUE THREAD

**Issue by krvajal** [jacobwilliams/json-fortran#275]
I am trying to use this library as part of my project. I use cmake as well for building it. I added the library as a git submodule and include it using cmake `add_directory('json-fortran')`  as part of my makefile. 
But when I try to compile it I get the following error mesages

```CMake Error at json-fortran/CMakeLists.txt:40 (file):
  file STRINGS file "/home/miguel/Desktop/autoconsistente/.VERSION" cannot be
  read.


CMake Error at json-fortran/CMakeLists.txt:41 (string):
  string sub-command REPLACE requires at least four arguments.


-- CMake build configuration for JSON-Fortran NOTFOUND.NOTFOUND.NOTFOUND
CMake Error at json-fortran/CMakeLists.txt:135 (set_target_properties):
  set_target_properties called with incorrect number of arguments.


CMake Error at json-fortran/CMakeLists.txt:142 (set_target_properties):
  set_target_properties called with incorrect number of arguments.


CMake Error at json-fortran/CMakeLists.txt:159 (file):
  file COPY cannot find "/home/miguel/Desktop/autoconsistente/media".
```
It seems it asumes that the project it at top level, but it is inside `/home/miguel/Desktop/autoconsistente/json-fortran`

How can I address this issuse?

**Comment by zbeekman** [comment]
This is a very non-standard way of using CMake with another project. `add_directory(json-fortran)` won't work because there are multiple project declarations and CMake packages aren't designed to be used that way.

The two best options are:

1) Install json-fortran on your system, then follow the [README.md's instructions for using CMake with your own project](https://github.com/jacobwilliams/json-fortran/blob/c46f234a7e1516a7328deb1a8f4f3c79608df523/README.md#building-the-library) by doing something like:
        `find_package ( jsonfortran-${CMAKE_Fortran_COMPILER_ID} 5.2.0 REQUIRED );
        include_directories ( "${jsonfortran_INCLUDE_DIRS}" )`
If you can't install json-fortran to a sensible location, you can also tell CMake to export the targets from the build directory with: `-DENABLE_BUILD_TREE_EXPORT:BOOL=1` when configuring with CMake (or if using `cmake-gui` just check the box) which will let CMake know where to search when you invoke `find_package`.
2) Use a [CMake "super build"](https://www.google.com/search?client=safari&rls=en&q=cmake+superbuild&ie=UTF-8&oe=UTF-8) build json-fortran. A good example of how to do this is [here](https://github.com/Sarcasm/cmake-superbuild).  Using a super build, you can also have CMake drive the download/fetch of the library, which means you may not even have to worry about using git submodules.

In general, you probably don't want to use git submodules unless you plan on significantly modifying json-fortran (and optionally contributing the changes back upstream). The use case for git submodules is generally smaller than most people thing at first sight, and a user or system wide installation, or a CMake super build is probably a better way to go.

**Comment by zbeekman** [comment]
p.s. there is a "PC" file so you can also use pacakage-config and autotools/automake, etc. for your main build system, if you prefer that to CMake.

**Comment by zbeekman** [comment]
@krvajal any updates? Did you have a chance to try any of my recommendations? Can this issue be closed?

**Comment by krvajal** [comment]
Yes you can close it now. 
		

		Get Outlook for iOS
	





On Mon, Jul 10, 2017 at 3:57 PM -0300, "zbeekman" <notifications@github.com> wrote:












@krvajal any updates? Did you have a chance to try any of my recommendations? Can this issue be closed?
