### ISSUE TITLE
CMake rules to control int and real kinds

### ISSUE THREAD

**Issue by milancurcic** [jacobwilliams/json-fortran#284]
I see that https://github.com/jacobwilliams/json-fortran/pull/239 added compile-time support for user-specified `int` and `real` kinds through `build.sh`. However, I don't see any way to control this when building with `cmake`.

Is there a way to specify these pre-processor (e.g. `-DREAL32`) macros via command line when invoking `cmake`? Would `CMakeLists.txt` need additional instructions?

**Comment by jacobwilliams** [comment]
That's a @zbeekman question! 😄

**Comment by zbeekman** [comment]
Thanks for tagging me. At the moment I don't believe this is implemented in
CMake. Let me take a look at build.sh and see if I can replicate the logic
there.

Ideally fp precision would be a *runtime* option rather than a compile time
option, but without widespread, portable support for parameterized derived
types this may be a PITA

**Comment by milancurcic** [comment]
Forgot that I had opened this, see my post in #238.
