### ISSUE TITLE
about json_file%info

### ISSUE THREAD

**Issue by caozigao** [jacobwilliams/json-fortran#315]
Hi, 
I have a json file like this:
```python
{"item": "a"}
```
When I call `json_file%info('item',n_children=n)`, it returns with n = 0. I can make it return with n = 1 if I write the json file as `{"item": ["a"]}`

Is there another way if I do not want to change the json file? Thanks!

**Comment by jacobwilliams** [comment]
`n_children` is only to tell you the number of elements in an array `[]` or object `{}`. So in this case, `item` is a string that has a value, but no children, so that's why it returns 0. You can use the other arguments of `info` to determine what type of variable it is (in this case, it's a `json_string`) and set it it 1 for these scalar cases if you want.

**Comment by caozigao** [comment]
Thanks!
