### ISSUE TITLE
create_array

### ISSUE THREAD

**Issue by mgovoni-devel** [jacobwilliams/json-fortran#360]
Why if I do this:
```fortran
CALL jcore%create_array(jval,"a")
CALL jfile%add("group",jval)
```
it doesn't create "group.a" : [], but "group" : []. 
If I want to create "group.a" : [], I need to repeat "a" twice:
```fortran
CALL jcore%create_array(jval,"a")
CALL jfile%add("group.a",jval)
```
I just want to understand if I am using the call correctly and this is the expected behavior. 
Thanks.

**Comment by jacobwilliams** [comment]
Confirmed. The `path` argument is the path to the thing you are adding. This is consistent with adding scalar quantiles like so:
```fortran
call jfile%add('group.b',1)
call jfile%add('group.c','hello')
```
which would create:
```javascript
{
  "group": {
   "b": 1,
   "c": "hello"
  }
}
```

So, this is the expected behavior. To avoid confusion, you could create the array with a blank name, then you don't have to have it there twice. So:
```fortran
call jcore%create_array(jval,'')  ! empty array
call jfile%add('group.a',jval)
```
which would create:
```javascript
{
  "group": {
   "a": []
  }
}
```

**Comment by mgovoni-devel** [comment]
Thanks.
