### ISSUE TITLE
speedup

### ISSUE THREAD

**Issue by valeryweber** [jacobwilliams/json-fortran#363]
Hi All
Would it be possible to speed up the library? For big files, it is about an order of magnitude slower than the python json module.
Many thanks
valery

**Comment by zbeekman** [comment]
Are you compiling with or without ucs4/Unicode support? The library is waaaaaayyyyyyyyyy faster without Unicode support.

**Comment by jacobwilliams** [comment]
Yes, there are probably some opportunities to speed things up.

One thing you can try: see the example `jf_test_09.F90`. If you read the file into a string first and then parse the string, it is a bit faster than reading it from a file (but will use more memory).

**Comment by zbeekman** [comment]
@valeryweber Did @jacobwilliams suggestion suit your needs?

**Comment by valeryweber** [comment]
it does help to pass a string to the parser, but still way slower than json python.
do you guys plan to give the library a speedup?
many thanks
valery

**Comment by jacobwilliams** [comment]
Somebody needs to do some comprehensive profiling on the code to see where the hot spots are. I would like to do this eventually, but not sure when I'll have time.

**Comment by zbeekman** [comment]
Jacob,

Can you please remind me: Is the big json file case we have in the repo a
sufficient test case to do some profiling?

We are using JSON-Fortran for some work with a Gov't agency (who
wants/needs and is implementing new ragged edge matrix support on their
fork, which I hope will be contributed back upstream) and while performance
is not (yet) an issue for them, I may be able to take a pass at profiling
with TAU Commander and ParaTools ThreadSpotter in the not-too distant
future.

Thanks!

**Comment by zbeekman** [comment]
@valeryweber any example input files you want to share with me for profiling would be most welcome.

@jacobwilliams I seem to remember an optimization where we were opening text files as if they were stream access binary files. I sent you a private message about the ragged edge array work.

**Comment by acroucher** [comment]
Does the speed issue happen mainly with JSON files containing large arrays? If so, I did some work on FSON (which JSON-Fortran was originally based on) to speed up array performance. I think similar things may have since been done to JSON-Fortran, but I'm not sure. FSON was originally doing some very inefficient things when iterating over arrays.

**Comment by jacobwilliams** [comment]
@zbeekman Yes, the stream access in enabled for non-unicode build. So, that is already there.

@acroucher If I remember correctly, I think I did get the `destroy_next` idea in the `destroy` routine from you. I don't think that's called during parsing though. I can't remember anything else related to arrays, do you? I can check the FSON history.

**Comment by acroucher** [comment]
@jacobwilliams There was at least one other commit related to speeding up array performance:
https://github.com/josephalevin/fson/commit/2a7f9bcc360bceef730d317a62ab989e1cc18a43

**Comment by jacobwilliams** [comment]
Thanks! I'll take a look.

**Comment by jacobwilliams** [comment]
I was also wondering... the core parsing routines (mostly inherited from FSON with modifications) are all recursive. I wonder if it would speed it up to flatten them all into one routine with a big loop and some case statements. Would that even be possible...hmmmmm....

**Comment by zbeekman** [comment]
It would very likely be faster but also very likely impossible or at least
a giant PITA.

**Comment by acroucher** [comment]
I got rid of at least some of the recursive stuff in FSON for performance reasons. It wasn't that hard. Some of it was specifically for large array handling (though that was more a case of stack overflow problems rather than speed): https://github.com/josephalevin/fson/commit/137cae2398545f2b6b251f8493c1b5fb5b62ce10

**Comment by jacobwilliams** [comment]
Note: I've gotten the normal (unformatted stream) JSON parser to be much faster by reading the file in chunks rather than one character at a time. Now, parsing the file normally is just about the same speed as reading it all in memory and parsing it from the string. On my laptop:
 * EXAMPLE 9a : 0.299  sec
 * EXAMPLE 9b : 0.283  sec
 * Python : 0.095 sec
So, not as fast as Python, but an improvements. I still want to try the non-recursive idea... stay tuned.
