### ISSUE TITLE
Questions: destroy, nullify, and finalization

### ISSUE THREAD

**Issue by rouson** [jacobwilliams/json-fortran#373]
I'm using json-fortran for the first time and have several questions about the example on "[Building a json file from scratch]":

1. Would it be worthwhile for `json_fortran` to define `final` subroutines that automate the invocation of `json%destroy(...)` when the corresponding object goes out of scope?  Then users wouldn't have to explicitly invoke the `destroy` procedure (except in certain specific cases such as the object declared in the main program in the mentioned example)?
2. Could such a `final` subroutine also perform the `nullify(inp)` that is in the example?
3. Suggestion: it would be good form to default-initialize the `json_value` pointers to `null()` in the example.
4. What is the intention of [`destroy_json_core`]?  Its only effect comes through the `intent(out)` declaration, which has two primary effects: 
  (a) causing the invocation of an associated `final` subroutine if any exists and 
  (b)  causing the declared object to become undefined. 
   but there appears to be no `final` subroutine and it's hard to see the value in a procedure that has only the effect of causing an object to become undefined.
5. What's the philosophy behind using pointers in json-fortran?  Could some of the pointers be replaced by `allocatable` objects to eliminate the possibility of memory leaks and dangling pointers?  (My days working a on big C++ library left me distrustful of any use of raw pointers that have not been encapsulated in a reference-counted pointer class.) 

[Building a json file from scratch]: 
https://github.com/jacobwilliams/json-fortran/wiki/Example-Usage#building-a-json-file-from-scratch
[`destroy_json_core`]: https://github.com/jacobwilliams/json-fortran/blob/master/src/json_value_module.F90#L806

**Comment by jacobwilliams** [comment]
Note that there is another way to use the library (see the `json_file` object). This encapsulates the linked-list that is created, and provides a mostly pointer-free interface (even for creating variables using the `add` methods). But, internally the pointers are still there, and you still have to call `json_file%destroy()` to free them. Also, I think not everything is available in this interface, so for some advanced usage you may still need to deal with the pointers yourself.

I did want to add a finalizer to `json_file` (there's a ticket for that I think). But, at the time, gfortran had some bug that was causing problems. I can revisit that. 

The `json_value` pointers are for creating a linked-list (really this is something json-fortran inherited from FSON). I don't know of any other way to do it though. (Types containing allocatable instances of the same type wasn't supported in the compilers, and I don't know if that would work for this case...but haven't given it much thought). 

I've not tried to implement any kind of reference-counting pointer scheme in Fortran (I think @zbeekman maybe have suggested that at one point also). That might be something interesting to look at... that could be a 3rd way to use the library.... but I suspect it would be quite tedious in Fortran and not cover all possible use cases due to some obscure language restriction. :) 

Yeah, the `destroy_json_core` routine I think was mainly a placeholder in case I ended up using pointers in the `json_core` type. But I never did (or maybe I did at one point but removed them). I guess it does deallocate a few allocatable variables in there? So, maybe not entirely useless?

**Comment by rouson** [comment]
Thanks for the quick reply.   I'll check out `json_file` and submit an issue if I have questions.  I would love to be able to avoid declaring pointers. 

A few more useful points: 
1. Gfortran 7 fixed the relevant [finalization bug].
2. Gfortran 8 supports allocatable components of recursive type.
3. It might suffice to inherit reference counting by simply extending the reference-counting class listed in a [paper] I co-authored.  All the code is in the paper, but I'll put it on GitHub too for convenience.
4. If I can't get `json_file` to work, then I'll try extending `json_core` and adding a final subroutine that calls the `destroy_json_core` subroutine on the parent `json_core` object. 


[finalization bug]: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=58175
[paper]: https://aip.scitation.org/doi/abs/10.1109/MCSE.2012.33

**Comment by rouson** [comment]
Also FWIW, there are ways to implement linked lists with arrays and indirect addressing instead of pointers or allocatable objects.  For example, if array element `list(i)` holds _i<sup>th</sup>_ item in the list, then the array `next(i)` holds the index value of the next item in the list.  A former grad student I mentored used this approach and found it both more robust (no chance of memory leaks or dangling pointers) and high-performing than pointer-based linked lists (probably owing to the difficulties of optimizing code containing pointers).  However, she used statically allocated arrays and halted execution if the array size was exhausted.   A more modern approach could use allocatable arrays and allocate blocks of elements as needed, where the block size would be determined by cost and performance issues associated with dynamic memory management.

**Comment by rouson** [comment]
It appears `json_file` provides what I need without requiring that I declare an pointers so I'll close this issue.
