### ISSUE TITLE
Is it possible to merge 2 json objects

### ISSUE THREAD

**Issue by Poolshark** [jacobwilliams/json-fortran#374]
Hi there! Me again...

I was wondering if it is possible to merge 2 json objects (guess json_file) and create a json file out of it.
Let's say I have:

**json 1** (is a json_file object)
```json
{
    "header": {
        "parent1": {
            "child1": 1,
            "child2": 2,
            "child3": 3 
        },
        "parent2": {
            "child1": 1.0,
            "child2": 2.0,
            "child3": 3.0
        }
    }
}
```

and **json 2** (is a json_file object)
```json
{
    "data": {
        "var1": [
            1,
            2,
            3 
        ],
        "var2": [
            1.0,
            2.0,
            3.0
        ]
    }
}
```
and I want to merge them into:
```json
{
    "header": {
        "parent1": {
            "child1": 1,
            "child2": 2,
            "child3": 3 
        },
        "parent2": {
            "child1": 1.0,
            "child2": 2.0,
            "child3": 3.0
        }
    },
     "data": {
        "var1": [
            1,
            2,
            3 
        ],
        "var2": [
            1.0,
            2.0,
            3.0
        ]
    }
}
```

**Comment by jacobwilliams** [comment]
Absolutely. Something like this:

```fortran


program merge

use json_module

implicit none

type(json_file) :: f1, f2, f3
type(json_core) :: json
type(json_value),pointer :: p_data,p_header
type(json_value),pointer :: p_data_copy,p_header_copy

call f1%load_file('file1.json')
call f2%load_file('file2.json')

call f1%get('header',p_header)
call f2%get('data',p_data)

! deep copy them:
call json%clone(p_header,p_header_copy)
call json%clone(p_data,p_data_copy)

call f3%add('header',p_header_copy)
call f3%add('data',p_data_copy)

! now, f3 is the merged file.
! f1 and f2 still exist as they did before

call f3%print_file()

! to clean up you would need to:
call f1%destroy()
call f2%destroy()
call f3%destroy()

end program merge
```

There are other ways to do this. Here I'm making a deep copy of the variables from `f1` and `f2` and making a new file `f3`. There's also a way to `remove()`the data from `f2` and add it to `f1` (which would leave `f2` as just `{}`).

**Comment by Poolshark** [comment]
Thanks again! This works in my dummy project.  Unfortunately I would need the header as a public object which I can use in another module to merge the data.

Is there any way of defining an object which I can use across modules even though I did the clean up?

**Comment by zbeekman** [comment]
> Is there any way of defining an object which I can use across modules even though I did the clean up?

I don't quite follow what you're asking here. The common way to create objects that are accessible from different scopes in modern Fortran is to declare a module. Then, the objects inside that module are accessed through use association. So you declare objects, procedures, types, interfaces, etc. that you want to be accessible to other entities in a module, then `USE` that module from the other programming scopes to import them via use association. In Jacobs example, you can create a module that contains the json variables and pointers you want to share between programming scopes, then `USE` that module in different scopes to access the variables and pointers.

Some care must be taken when doing copying, since the data structures are built with pointers. So take care to choose between deep and shallow copies. And deallocate memory and/or nullify pointers when they are no longer needed, keeping in mind that with shallow copies, you may accidentally be deallocating/nullifying a component of an object you still care about.
