### ISSUE TITLE
Coverage info

### ISSUE THREAD

**Issue by zbeekman** [jacobwilliams/json-fortran#63]
Once #30 and #27 are wrapped up, it would be nice to get test coverage info, and maybe use coveralls. I think this should be straight forwards to setup, using the C/C++ example/howto. I doubt any changes need to be made for Fortran.

**Comment by jacobwilliams** [comment]
Agree.  I was actually just recently looking into this...

**Comment by szaghi** [comment]
Dear @zbeekman and @jacobwilliams 

I found very useful [cpp-coveralls](https://github.com/eddyxu/cpp-coveralls).

I have added some support to FoBiS.py for coverage analysis, presently with only gfortran (I am now working on Intel ifort support): just add `-coverage` option to build switches. 

It works very well on local repo, but with travis-ci I have a minor bug that prevent the coverage analysis data to be uploaded to coveralls.io (see [this](https://github.com/eddyxu/cpp-coveralls/issues/73)). An example is in [BeFoR64](https://github.com/szaghi/BeFoR64).

I am now working on improve the coverage support of FoBiS.py, e.g. I like the gcovr script...

See you soon.

**Comment by zbeekman** [comment]
@szaghi Thanks, and I was planning on using cpp-coveralls. I saw your bug report there… do you know if it will work alright without the `-b` flag?

@jacobwilliams as soon as I hear back from @bruceravel who very kindly agreed to help update the SConstruct file, I should have a PR for #27, #30, #42 and coverage support. FTI I’m going to split tests 1 and 8 into 1a, 1b, 1c and 8a, 8b, 8c so that the output can be checked by jsonlint.

**Comment by szaghi** [comment]
@zbeekman No, I have not tested without `-b`: on my local repo without `-b` coveralls fails because it does not find the sources (gcov is runned into the root that contains build/obj/*.gcno src/*f90... thus the `-b` is mandatory), but with this switch on travis-ci repo seems that no analysis is performed (thus I had to manually upload the analysis to coveralls.io).

**Comment by szaghi** [comment]
@zbeekman I have just added the support for also intel coverage (both for compiling phase and post-test coverage analysis phase). It is not yet documented, but the CLI help messages are presented.

See you monday.

**Comment by zbeekman** [comment]
I can’t seem to get the FoBiS.py build to output coverage info for the library. It’s weird because I can get CMake to do it. Even manually specifying `-ftest-coverage -fprofile-arcs` in the FoBiS cflags and lflags doesn’t seem to work for me. With cmake the issue is I can’t get it to upload

**Comment by szaghi** [comment]
Give me some hours and I will upload more documentation.

Forvnow, FoBiS has two -coverage option:

+ during building phase
+ a post bulding *rule* analysis

### coveralls

Firstly you must build the code in coverage mode:

```bash
FoBiS.py build -compiler gnu -coverage ...
```

After you must run the built program(s) (your library tests I guess) in
order to collect the coverage data that must be analized with gcov.

After running tge instrumented code into the obj dirs there are the
coverage data. Now you can run cpp-coverall, in my set-up I need the -b
switch:

```bash
coveralls -b .
```
This will run the post processing gcov tool producing the coverage
analysis. Unlucy, I failed to upload this data from travis, because on
travis `coveralls` does not produce the data... Consequently I have
uploaded the data manually with `-t #token` switch.

### local coverage analysis

The second FoBis.py rule for coverage is an intrinsic rule: it is intended
to run the post-processing coverage analisys tool (cpp-coveralls in the
previous example) locally. Presently, for this local analysis I have
decided for using `gcovr` for gnu and for intel its own tool.

In this scdnario you must do:

Build with coverage
```bash
FoBiS.py build -compiler gnu -coverage ...
```
run your tests
```bash
./tests
```
Analize the coverage data
```bash
FoBiS.py run -coverage gnu
```
Note that for this local analysis you can use also the intel compiler.

See you later.

**Comment by zbeekman** [comment]
@szaghi Thanks for additional information. I have followed your instructions, think I have finally got things working. By the way, for the latest release of FoBiS.py there doesn’t seem to be a `run` command, only `build | clean | rule` but as I said I think I got things working. I should be submitting a PR soon, after running some tests.

**Comment by zbeekman** [comment]
One major problem I ran into is that gcov  will segfault if it doesn’t match the same version as gfortran. To get this working you need to add `sudo apt-get install binutils` somewhere after you add the toolchain-r/test PPA and then you need to put a symbolic link named `gcov` somewhere on your path that points to `/usr/bin/gcov-4.9` PR incoming shortly…

**Comment by zbeekman** [comment]
@jacobwilliams could you make yourself an account at https://coveralls.io/ by logging in with your GitHub credentials and then enabling the json-fortran repo?

**Comment by jacobwilliams** [comment]
This is great!

**Comment by zbeekman** [comment]
Thanks… I was considering moving the call to gcov from .travis.yml to the build script… not sure though. Also, there’s probably a way to do it without calling gcov explicitly, by letting cpp-coveralls/coveralls call it, but I was having trouble figuring out the excludes, and getting frustrated so I just called gcov explicitly in .travis.yml and then told coveralls not to run it.
